
name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - main
      - feature/*

variables:
  - name: solution
    value: '**/*.sln'
  - name: buildPlatform
    value: Any CPU
  - name: buildConfiguration
    value: Release

stages:
- stage: 'Build'
  displayName: 'Build Test Automation'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'windows-latest'
    variables:
      - template: templates/variables-build.yml      
    steps:
      - template: steps-build-and-test.yaml
  

- stage: 'Run'
  displayName: 'Run tests'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: 'Build'
    displayName: 'run job against sandbox'
    pool:
      vmImage: 'windows-latest'   
    steps:
      - checkout: none

      - task: DownloadPipelineArtifact@2
        displayName: 'Download test tools'
        condition: succeeded()
        inputs:
          buildType: 'current'
          artifact: tests

      - task: VSTest@2
        displayName: Run tests
        inputs:
          platform: $(buildPlatform)
          configuration: $(buildConfiguration)
          testAssemblyVer2: |
            **\*Specs.dll
            !**\*TestAdapter.dll
            !**\obj\**  
          searchFolder: $(Pipeline.Workspace)
          testRunTitle: End-to-end tests - Test
          runSettingsFile: $(Pipeline.Workspace)/CI.runsettings
          # Handled via SpecFlow+ Runner
          rerunFailedTests: false
          publishRunAttachments: true
          uiTests: true 
          runInParallel: true