
name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - main
      - feature/*

stages:
- stage: 'Build'
  displayName: 'Build Enricher Service'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      - template: templates/variables-build.yml      
    steps:
      - template: steps-build-and-test.yaml