GRANT CONNECT ON DATABASE "ncea-classifier" TO "TSTNCEINFID1404";

GRANT pg_read_all_data, pg_write_all_data TO "TSTNCEINFID1404";
GRANT ALL ON SCHEMA public TO "TSTNCEINFID1404";
GRANT ALL ON ALL TABLES IN SCHEMA public TO "TSTNCEINFID1404";
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO "TSTNCEINFID1404";
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO "TSTNCEINFID1404";
GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA public TO "TSTNCEINFID1404";